version: "3.7"

services:
  local_ses:
    image: node:18.1.0
    working_dir: /local_ses
    ports:
      - 8005:8005
    volumes:
      - ./local_ses:/local_ses
    tty: true
    command: "node index.js"
